import * as cdk from 'aws-cdk-lib';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as acm from 'aws-cdk-lib/aws-certificatemanager';
import * as route53 from 'aws-cdk-lib/aws-route53';
import * as targets from 'aws-cdk-lib/aws-route53-targets';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import { Construct } from 'constructs';
import * as path from 'path';

export class HostingStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Required environment variables
    const domainName = process.env.DOMAIN_NAME;
    const hostedZoneId = process.env.HOSTED_ZONE_ID;

    if (!domainName || !hostedZoneId) {
      throw new Error('Missing required environment variables: DOMAIN_NAME, HOSTED_ZONE_ID');
    }

    const wildcardDomain = `*.${domainName}`;

    // Import existing hosted zone
    const hostedZone = route53.HostedZone.fromHostedZoneAttributes(this, 'HostedZone', {
      hostedZoneId,
      zoneName: domainName,
    });

    // Create wildcard certificate with DNS validation
    const certificate = new acm.Certificate(this, 'WildcardCertificate', {
      domainName: wildcardDomain,
      validation: acm.CertificateValidation.fromDns(hostedZone),
    });

    // S3 Bucket for hosting static sites (name auto-generated by CloudFormation)
    const bucket = new s3.Bucket(this, 'SitesBucket', {
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      versioned: true,
      removalPolicy: cdk.RemovalPolicy.RETAIN,
    });

    // CloudFront Function for subdomain routing
    const routingFunction = new cloudfront.Function(this, 'SubdomainRouter', {
      code: cloudfront.FunctionCode.fromInline(`
function handler(event) {
  var request = event.request;
  var host = request.headers.host.value;
  var uri = request.uri;

  var domainName = '${domainName}';
  var baseDomain = '.' + domainName;

  // Extract subdomain
  var subdomain = '';
  if (host.endsWith(baseDomain)) {
    subdomain = host.slice(0, -baseDomain.length);
  } else if (host === domainName) {
    request.uri = '/_errors/404.html';
    return request;
  }

  // Validate subdomain (alphanumeric and hyphens only)
  if (!subdomain || !/^[a-z0-9][a-z0-9-]*[a-z0-9]$|^[a-z0-9]$/.test(subdomain)) {
    request.uri = '/_errors/404.html';
    return request;
  }

  // Route to subdomain folder
  if (uri.endsWith('/')) {
    request.uri = '/' + subdomain + uri + 'index.html';
  } else if (!/\\.[a-zA-Z0-9]+$/.test(uri)) {
    request.uri = '/' + subdomain + uri + '/index.html';
  } else {
    request.uri = '/' + subdomain + uri;
  }

  return request;
}
      `),
      runtime: cloudfront.FunctionRuntime.JS_2_0,
      comment: 'Routes subdomain requests to S3 folders',
    });

    // Aggressive cache policy (invalidate on deploy)
    const cachePolicy = new cloudfront.CachePolicy(this, 'AggressiveCachePolicy', {
      comment: 'Aggressive caching - invalidate on deploy',
      defaultTtl: cdk.Duration.days(7),
      minTtl: cdk.Duration.days(1),
      maxTtl: cdk.Duration.days(365),
      enableAcceptEncodingGzip: true,
      enableAcceptEncodingBrotli: true,
    });

    // Security headers response policy
    const responseHeadersPolicy = new cloudfront.ResponseHeadersPolicy(this, 'SecurityHeaders', {
      securityHeadersBehavior: {
        contentTypeOptions: { override: true },
        frameOptions: {
          frameOption: cloudfront.HeadersFrameOption.DENY,
          override: true,
        },
        strictTransportSecurity: {
          accessControlMaxAge: cdk.Duration.days(365),
          includeSubdomains: true,
          override: true,
        },
        xssProtection: {
          protection: true,
          modeBlock: true,
          override: true,
        },
      },
    });

    // CloudFront Distribution
    const distribution = new cloudfront.Distribution(this, 'Distribution', {
      defaultBehavior: {
        origin: origins.S3BucketOrigin.withOriginAccessControl(bucket),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        functionAssociations: [{
          function: routingFunction,
          eventType: cloudfront.FunctionEventType.VIEWER_REQUEST,
        }],
        responseHeadersPolicy,
        cachePolicy,
      },
      domainNames: [wildcardDomain],
      certificate,
      enableIpv6: true,
      httpVersion: cloudfront.HttpVersion.HTTP2_AND_3,
      errorResponses: [
        {
          httpStatus: 403,
          responseHttpStatus: 404,
          responsePagePath: '/_errors/404.html',
          ttl: cdk.Duration.days(1),
        },
        {
          httpStatus: 404,
          responseHttpStatus: 404,
          responsePagePath: '/_errors/404.html',
          ttl: cdk.Duration.days(1),
        },
      ],
    });

    // Route53 records
    new route53.ARecord(this, 'WildcardARecord', {
      zone: hostedZone,
      recordName: '*',
      target: route53.RecordTarget.fromAlias(new targets.CloudFrontTarget(distribution)),
    });

    new route53.AaaaRecord(this, 'WildcardAAAARecord', {
      zone: hostedZone,
      recordName: '*',
      target: route53.RecordTarget.fromAlias(new targets.CloudFrontTarget(distribution)),
    });

    // Deploy error pages to S3
    new s3deploy.BucketDeployment(this, 'DeployErrorPages', {
      sources: [s3deploy.Source.asset(path.join(__dirname, '../_errors'))],
      destinationBucket: bucket,
      destinationKeyPrefix: '_errors',
    });

    // Outputs
    new cdk.CfnOutput(this, 'BucketName', {
      value: bucket.bucketName,
      description: 'S3 bucket for hosting sites',
    });

    new cdk.CfnOutput(this, 'DistributionId', {
      value: distribution.distributionId,
      description: 'CloudFront distribution ID',
    });

    new cdk.CfnOutput(this, 'DistributionDomain', {
      value: distribution.distributionDomainName,
      description: 'CloudFront distribution domain',
    });
  }
}
